
services:
  finazappback:
    build: ./backend/docker
    # Puerto 8080 
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/var/www/html
    container_name: finazappback
    deploy:
      resources:
        limits:
          cpus: "0.2"       # 20% de CPU
          memory: 300M      # 300MB de memoria
        reservations:
          cpus: "0.1"       # 10% de CPU dedicado
          memory: 150M      # 150MB de memoria dedicada

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: finazapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.3"       # 30% de CPU
          memory: 512M      # 512MB de memoria
        reservations:
          cpus: "0.15"      # 15% de CPU dedicado
          memory: 256M      # 256MB de memoria dedicada
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql-db
    deploy:
      resources:
        limits:
          cpus: "0.2"       # 20% de CPU
          memory: 200M      # 200MB de memoria
        reservations:
          cpus: "0.1"       # 10% de CPU dedicado
          memory: 100M      # 100MB de memoria dedicada

  finazappfront:
    build:
      context: ./angular/frontend
      dockerfile: Dockerfile
    container_name: finazappfront
    ports:
      - "80:80"
    depends_on:
      - finazappback
    deploy:
      resources:
        limits:
          cpus: "0.3"       # 30% de CPU
          memory: 300M      # 300MB de memoria
        reservations:
          cpus: "0.15"      # 15% de CPU dedicado
          memory: 200M      # 200MB de memoria dedicada