apiVersion: v1
kind: Service
metadata:
  name: finazapp-front-service
  labels:
    app: finazapp-front
spec:
  ports:
    - name: finazapp-front
      port: 80
      nodePort: 30101
  type: NodePort
  selector: 
    app: finazapp-front
    